### ISSUE TITLE
Error: command fund-test-wallet not found

### ISSUE THREAD

**Issue by hamsingh** [christroutner/benchmark-bch#6]
When installing the package using npm on ubuntu 18.04 this error appears after executing 
`sudo slp-cli-wallet fund-test-wallet -n --name=testnet`
` ›   Error: command fund-test-wallet not found`

Have I installed the package or used it incorrectly?

EDIT: I have created the wallet and works fine. The commands that don't seem to work are the commands added in benchmark-bch repo where as the slp-cli-wallet commands work. Is there a way to run the benchmark-bch repo commands?

**Comment by christroutner** [comment]
There is something broken when installing the npm package with the `-g` command. The software is intended to be run by cloning the repository and running it with the `./bin/run` command inside the cloned git directory:
https://github.com/christroutner/benchmark-bch#install-dev-environment

**Comment by christroutner** [comment]
Also, this app is currently set up to use the temporary infrastructure I've set up for running my benchmark tests. You'll need to set up your own infrastructure in order to run these tests.

**Comment by hamsingh** [comment]
Thanks for that. In terms of infrastructure for these tests have you got any documentation for setup/configuration? I am trying to do my own stress tests for a ABC full node on the RPi 4. TIA

**Comment by christroutner** [comment]
The benchmark tests are based on the 'Cash Stack' model of infrastructure:
https://troutsblog.com/research/bitcoin-cash/how-to-bch-full-stack-developer

**Comment by christroutner** [comment]
The different infrastructure components of the Cash Stack can be pointed to by the [config file](https://github.com/christroutner/benchmark-bch/blob/master/config/index.js)
